# infrastructure/docker/Dockerfile.engine
FROM cgr.dev/chainguard/python@sha256:5a2c58619a41d1c1c1b474ee6238c15ad0fd9d7a572f9b521976a5f9b8909e12 AS builder

USER 0
ENV PATH=/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_ROOT_USER_ACTION=ignore
WORKDIR /app
COPY apps/engine/requirements.txt .
RUN python -m venv /opt/venv \
    && pip install --no-cache-dir -r requirements.txt \
    && pip uninstall -y pip setuptools wheel
COPY apps/engine/ .
COPY packages/shared-types/proto/solver.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. solver.proto

FROM cgr.dev/chainguard/python@sha256:6d71f8dbd199350964ce8b10d50fb9d4d8e2bd50316f3a1821dbdc6eef5252fb AS runner

ENV HOME=/home/nonroot \
    PATH=/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
WORKDIR /app
COPY --from=builder --chown=65532:65532 /opt/venv /opt/venv
COPY --from=builder --chown=65532:65532 /app /app
USER 65532:65532
ENTRYPOINT []

EXPOSE 8000 50051
CMD ["python", "main.py"]
