# syntax=docker/dockerfile:1.7

FROM golang:1.26.6-alpine3.23@sha256:e57c41c1d5864341031181b0db34b9a537bb5773eb6428e4e5bdaea0f9135406 AS build
RUN apk add --no-cache git
RUN git init /src \
    && cd /src \
    && git remote add origin https://github.com/grafana/tempo.git \
    && git fetch --depth 1 origin 4aeafc237b8d9a8d62e45735131e8a89eb741a00 \
    && git checkout --detach 4aeafc237b8d9a8d62e45735131e8a89eb741a00 \
    && test "$(git rev-parse HEAD)" = "4aeafc237b8d9a8d62e45735131e8a89eb741a00"
WORKDIR /src
RUN go get github.com/buger/jsonparser@v1.1.2 \
      github.com/antchfx/xpath@v1.3.6 \
      github.com/go-jose/go-jose/v4@v4.1.4 \
      github.com/apache/thrift@v0.23.0 \
      github.com/prometheus/prometheus@v0.311.3 \
      go.opentelemetry.io/otel@v1.43.0 \
      go.opentelemetry.io/otel/sdk@v1.43.0 \
      golang.org/x/crypto@v0.53.0 \
      golang.org/x/net@v0.56.0 \
      golang.org/x/text@v0.39.0 \
      google.golang.org/grpc@v1.82.1
RUN CGO_ENABLED=0 GOAMD64=v2 go build -mod=mod -trimpath \
    -ldflags '-s -w -X main.Branch=HEAD -X main.Revision=4aeafc237b8d9a8d62e45735131e8a89eb741a00 -X main.Version=2.10.3' \
    -o /out/tempo ./cmd/tempo

FROM grafana/tempo:2.10.3@sha256:cac9de2ac9f6da8efca5b64b690a7cb8c786a0c49cac7b4517dd1b0089a6c703
COPY --from=build /out/tempo /tempo
