# syntax=docker/dockerfile:1.7

FROM golang:1.26.6-alpine3.23@sha256:e57c41c1d5864341031181b0db34b9a537bb5773eb6428e4e5bdaea0f9135406 AS build
RUN apk add --no-cache git
RUN git init /src \
    && cd /src \
    && git remote add origin https://github.com/grafana/tempo.git \
    && git fetch --depth 1 origin 1900ed7bb5cad1a3edc285783d7d4ac4278337dc \
    && git checkout --detach 1900ed7bb5cad1a3edc285783d7d4ac4278337dc \
    && test "$(git rev-parse HEAD)" = "1900ed7bb5cad1a3edc285783d7d4ac4278337dc"
WORKDIR /src
RUN CGO_ENABLED=0 GOAMD64=v2 go build -trimpath \
    -ldflags '-s -w -X main.Branch=HEAD -X main.Revision=1900ed7bb5cad1a3edc285783d7d4ac4278337dc -X main.Version=3.0.3' \
    -o /out/tempo ./cmd/tempo

FROM grafana/tempo:3.0.3@sha256:0296560ac66f8a3600d7fb3014a52c189d4d9c3549ad6ff441bf2409855d68d5
COPY --from=build /out/tempo /tempo
