# syntax=docker/dockerfile:1.7

FROM golang:1.26.6-alpine3.23@sha256:e57c41c1d5864341031181b0db34b9a537bb5773eb6428e4e5bdaea0f9135406 AS build
WORKDIR /src
COPY infrastructure/docker/otelcol-builder.yaml /src/otelcol-builder.yaml
RUN go install go.opentelemetry.io/collector/cmd/builder@v0.159.0 \
    && builder --skip-compilation --config=/src/otelcol-builder.yaml \
    && cd /src/otelcol-contrib \
    && go get golang.org/x/mod@v0.40.0 \
    && go mod tidy \
    && CGO_ENABLED=0 go build -buildvcs=false -trimpath -ldflags '-s -w' -o /out/otelcol-contrib .

FROM otel/opentelemetry-collector-contrib:0.159.0@sha256:1f2c54a30e713fac6b3ae77a1ec84010c2007e29ced8ec666214fc2f6739c1cc
COPY --from=build /out/otelcol-contrib /otelcol-contrib
