# syntax=docker/dockerfile:1.7

FROM postgres:16-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685
RUN apk upgrade --no-cache \
    && apk add --no-cache su-exec \
    && grep -q 'gosu postgres' /usr/local/bin/docker-entrypoint.sh \
    && sed -i 's/gosu postgres/su-exec postgres/g' /usr/local/bin/docker-entrypoint.sh \
    && ! grep -q 'gosu postgres' /usr/local/bin/docker-entrypoint.sh \
    && rm -f /usr/local/bin/gosu
