# syntax=docker/dockerfile:1.7

FROM golang:1.26.6-alpine3.23@sha256:e57c41c1d5864341031181b0db34b9a537bb5773eb6428e4e5bdaea0f9135406 AS build
RUN apk add --no-cache git
RUN git init /src \
    && cd /src \
    && git remote add origin https://github.com/grafana/loki.git \
    && git fetch --depth 1 origin 5003600d7c787b5f047c8d1b0198559471b0caa5 \
    && git checkout --detach 5003600d7c787b5f047c8d1b0198559471b0caa5 \
    && test "$(git rev-parse HEAD)" = "5003600d7c787b5f047c8d1b0198559471b0caa5"
WORKDIR /src
RUN CGO_ENABLED=0 go build -trimpath -tags netgo \
    -ldflags '-s -w -X github.com/grafana/loki/v3/pkg/util/build.Branch=HEAD -X github.com/grafana/loki/v3/pkg/util/build.Version=3.7.6 -X github.com/grafana/loki/v3/pkg/util/build.Revision=5003600d7c787b5f047c8d1b0198559471b0caa5 -X github.com/grafana/loki/v3/pkg/util/build.BuildUser=lunchlineup -X github.com/grafana/loki/v3/pkg/util/build.BuildDate=2026-08-20T00:00:00Z' \
    -o /out/loki ./cmd/loki

FROM grafana/loki:3.7.6@sha256:efd47c67f9bac88ca29bcf8cb997d9ab29d1848bd0aff579282295542a745952
COPY --from=build /out/loki /usr/bin/loki
