# syntax=docker/dockerfile:1.7

FROM golang:1.26.6-alpine3.23@sha256:e57c41c1d5864341031181b0db34b9a537bb5773eb6428e4e5bdaea0f9135406 AS build
# Caddy v2.11.4 resolves to upstream commit e2eee6a7fce366321294c9c2a79f3146891dcbdf.
WORKDIR /build
RUN go mod init github.com/lunchlineup/caddy-build \
    && go get github.com/caddyserver/caddy/v2@v2.11.4 \
    && go get golang.org/x/net@v0.56.0 golang.org/x/text@v0.39.0 google.golang.org/grpc@v1.82.1
RUN <<'EOF' sh
cat > main.go <<'GO'
package main

import (
	_ "time/tzdata"

	caddycmd "github.com/caddyserver/caddy/v2/cmd"
	_ "github.com/caddyserver/caddy/v2/modules/standard"
)

func main() {
	caddycmd.Main()
}
GO
go mod tidy
CGO_ENABLED=0 go build -trimpath \
  -ldflags '-s -w -X github.com/caddyserver/caddy/v2.CustomVersion=v2.11.4-lunchlineup' \
  -o /out/caddy .
go version -m /out/caddy | grep -F 'github.com/caddyserver/caddy/v2' | grep -F 'v2.11.4'
EOF

FROM caddy:2-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
RUN apk upgrade --no-cache \
    && apk del --no-cache curl
COPY --from=build /out/caddy /usr/bin/caddy
