# syntax=docker/dockerfile:1.7

FROM golang:1.26.6-alpine3.23@sha256:e57c41c1d5864341031181b0db34b9a537bb5773eb6428e4e5bdaea0f9135406 AS build
RUN apk add --no-cache git nodejs npm
RUN git init /src \
    && cd /src \
    && git remote add origin https://github.com/prometheus/alertmanager.git \
    && git fetch --depth 1 origin 085f0ef7eb41da24cab8cd000f1345b6250f2edb \
    && git checkout --detach 085f0ef7eb41da24cab8cd000f1345b6250f2edb \
    && test "$(git rev-parse HEAD)" = "085f0ef7eb41da24cab8cd000f1345b6250f2edb"
WORKDIR /src
RUN cd ui/app \
    && npm ci \
    && npm run build
RUN go get golang.org/x/mod@v0.40.0 \
    && CGO_ENABLED=0 go build -buildvcs=false -trimpath -ldflags '-s -w' -o /out/alertmanager ./cmd/alertmanager \
    && CGO_ENABLED=0 go build -buildvcs=false -trimpath -ldflags '-s -w' -o /out/amtool ./cmd/amtool

FROM prom/alertmanager:v0.34.0@sha256:690c7b525f4367aa91f73e2f91c632206d32e97c6384bdbf2fb7a861b420340d
COPY --from=build /out/alertmanager /bin/alertmanager
COPY --from=build /out/amtool /bin/amtool
