import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
const script=resolve(import.meta.dirname,'../../scripts/write-internal-ci-release-manifest.mjs'),sha='1'.repeat(40),tree='2'.repeat(40),baseline='3'.repeat(40),pipeline='4'.repeat(64),hash=(b)=>createHash('sha256').update(b).digest('hex');
function fixture(){const scratch=mkdtempSync(join(tmpdir(),'ll-manifest-')),artifact=join(scratch,'artifact'),runner=join(scratch,'runner'),runRoot=join(runner,'lunchlineup-source-run-1'),scan=join(runRoot,'scan'),build=join(runRoot,'build'),images=join(artifact,'images');for(const p of [join(artifact,'source'),images,join(scan,'.git'),join(build,'.git'),join(build,'infrastructure/ci')])mkdirSync(p,{recursive:true});const proof={version:1,kind:'lunchlineup-internal-ci-source-proof',status:'passed',repository:'tuckerplee/LunchLineup',sourceRef:'refs/heads/internal-beta-candidate',sourceSha:sha,remoteCandidateSha:sha,treeSha:tree,baselineRef:'refs/heads/main',baselineSha:baseline,baselineTreeSha:baseline,pipelineSha256:pipeline,runId:'run-1',originalCheckoutClean:true,scanCloneVerified:true,buildCloneVerified:true,gitAlternatesRejected:true,verifiedAt:new Date().toISOString()},proofPath=join(artifact,'source/source-proof.json');writeFileSync(proofPath,JSON.stringify(proof));const contextPath=join(runRoot,'source-context.json');writeFileSync(contextPath,JSON.stringify({version:1,kind:'lunchlineup-internal-ci-source-context',repository:proof.repository,runId:proof.runId,runRoot,sourceRef:proof.sourceRef,sourceSha:sha,treeSha:tree,remoteCandidateSha:sha,baselineRef:proof.baselineRef,baselineSha:baseline,pipelineSha256:pipeline,sourceProofPath:proofPath,scanSourcePath:scan,buildSourcePath:build,artifactRoot:artifact,evidenceRoot:artifact}));
const digest='a'.repeat(64),compose={services:{api:{image:`lunchlineup-internal-ci/api:${sha}`,healthcheck:{}},webhook:{image:`lunchlineup-internal-ci/api:${sha}`,healthcheck:{}},web:{image:`lunchlineup-internal-ci/web:${sha}`,healthcheck:{}},redis:{image:`redis:7@sha256:${digest}`,healthcheck:{}}}},composePath=join(artifact,'compose-config.json');writeFileSync(composePath,JSON.stringify(compose));writeFileSync(join(build,'infrastructure/ci/internal-beta-runtime-services.json'),JSON.stringify({services:Object.fromEntries(Object.keys(compose.services).map(n=>[n,{}]))}));const publicContract={sourceSha:sha,publicBuildConfigSha256:'b'.repeat(64),nextPublicApiUrl:'/api/v2',nextPublicAppOrigin:'https://beta.lunchlineup.com',nextPublicAppUrl:'https://beta.lunchlineup.com',nextPublicAppEnv:'production',nextPublicSignupMode:'closed_beta'},publicPath=join(artifact,'public-build-contract.json');writeFileSync(publicPath,JSON.stringify(publicContract));
const metas={api:{artifactName:'api',composeServices:['api','webhook'],imageRef:`lunchlineup-internal-ci/api:${sha}`,localImageId:`sha256:${'c'.repeat(64)}`},web:{artifactName:'web',composeServices:['web'],imageRef:`lunchlineup-internal-ci/web:${sha}`,localImageId:`sha256:${'d'.repeat(64)}`},redis:{artifactName:'redis',composeServices:['redis'],imageRef:`redis:7@sha256:${digest}`,localImageId:`sha256:${'e'.repeat(64)}`}};for(const [name,meta]of Object.entries(metas)){const bytes=Buffer.from(`archive-${name}`),archive=join(images,`${name}.tar.gz`);writeFileSync(archive,bytes);Object.assign(meta,{archiveFile:`images/${name}.tar.gz`,archiveSha256:hash(bytes),archiveBytes:bytes.length});writeFileSync(join(images,`${name}.image.json`),JSON.stringify(meta));}const output=join(artifact,'release-manifest.json'),args=['--source-context',contextPath,'--compose-config',composePath,'--public-build-contract',publicPath,'--image-directory',images,'--output',output],env={...process.env,CI_COMMIT_SHA:sha,CI_RUN_ID:'run-1',RUNNER_TEMP:runner};return{scratch,artifact,build,images,compose,composePath,publicContract,publicPath,metas,output,args,env};}
const run=(f)=>spawnSync(process.execPath,[script,...f.args],{env:f.env,encoding:'utf8'}),writeMeta=(f,n)=>writeFileSync(join(f.images,`${n}.image.json`),JSON.stringify(f.metas[n]));
test('complete resolved Compose image inventory writes one exact shared-image manifest',()=>{const f=fixture();try{const r=run(f);assert.equal(r.status,0,r.stderr);const m=JSON.parse(readFileSync(f.output));assert.equal(m.sourceSha,sha);assert.deepEqual(m.images.api.composeServices,['api','webhook']);assert.equal(Object.keys(m.images).length,3);}finally{rmSync(f.scratch,{recursive:true,force:true});}});
for(const [name,mutate]of[
 ['missing Compose service',(f)=>{delete f.compose.services.webhook;writeFileSync(f.composePath,JSON.stringify(f.compose));}],
 ['extra Compose service',(f)=>{f.compose.services.ghost={image:`lunchlineup-internal-ci/ghost:${sha}`};writeFileSync(f.composePath,JSON.stringify(f.compose));}],
 ['mutable third-party tag',(f)=>{f.compose.services.redis.image='redis:7';f.metas.redis.imageRef='redis:7';writeFileSync(f.composePath,JSON.stringify(f.compose));writeMeta(f,'redis');}],
 ['missing first-party archive',(f)=>unlinkSync(join(f.images,'web.tar.gz'))],
 ['wrong archive digest',(f)=>{f.metas.web.archiveSha256='9'.repeat(64);writeMeta(f,'web');}],
 ['wrong archive byte count',(f)=>{f.metas.web.archiveBytes++;writeMeta(f,'web');}],
 ['wrong local image ID',(f)=>{f.metas.web.localImageId='sha256:bad';writeMeta(f,'web');}],
 ['shared image duplicated',(f)=>{const duplicate={...f.metas.api,artifactName:'api-copy',archiveFile:'images/api-copy.tar.gz'};writeFileSync(join(f.images,'api-copy.tar.gz'),'copy');duplicate.archiveSha256=hash('copy');duplicate.archiveBytes=4;writeFileSync(join(f.images,'api-copy.image.json'),JSON.stringify(duplicate));}],
 ['shared image missing consumer',(f)=>{f.metas.api.composeServices=['api'];writeMeta(f,'api');}],
 ['web public-build digest mismatch',(f)=>{f.publicContract.nextPublicAppUrl='https://wrong.invalid';writeFileSync(f.publicPath,JSON.stringify(f.publicContract));}],
 ['wrong candidate SHA',(f)=>{f.publicContract.sourceSha='9'.repeat(40);writeFileSync(f.publicPath,JSON.stringify(f.publicContract));}],
 ['unreferenced archive',(f)=>writeFileSync(join(f.images,'extra.tar.gz'),'extra')],
])test(`release manifest rejects ${name}`,()=>{const f=fixture();try{mutate(f);assert.notEqual(run(f).status,0);}finally{rmSync(f.scratch,{recursive:true,force:true});}});
test('release manifest rejects a symlinked archive',{skip:process.platform==='win32'},()=>{const f=fixture();try{unlinkSync(join(f.images,'web.tar.gz'));symlinkSync(join(f.images,'api.tar.gz'),join(f.images,'web.tar.gz'));assert.notEqual(run(f).status,0);}finally{rmSync(f.scratch,{recursive:true,force:true});}});
