import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import { REQUIRED_INTERNAL_BETA_GATES } from '../../scripts/internal-ci-policy.mjs';
const builder=resolve(import.meta.dirname,'../../scripts/build-internal-ci-candidate-receipt.mjs'),sha='1'.repeat(40),tree='2'.repeat(40),baseline='3'.repeat(40),pipeline='4'.repeat(64),h=(v)=>createHash('sha256').update(v).digest('hex');
function fixture(){const scratch=mkdtempSync(join(tmpdir(),'ll-receipt-')),artifact=join(scratch,'artifact'),runner=join(scratch,'runner'),runRoot=join(runner,'lunchlineup-source-run-1'),scan=join(runRoot,'scan'),build=join(runRoot,'build');for(const p of [join(artifact,'source'),join(artifact,'gates'),join(artifact,'details'),join(artifact,'evidence'),join(artifact,'images'),join(artifact,'sbom'),join(artifact,'trivy'),join(scan,'.git'),join(build,'.git')])mkdirSync(p,{recursive:true});const proof={version:1,kind:'lunchlineup-internal-ci-source-proof',status:'passed',repository:'tuckerplee/LunchLineup',sourceRef:'refs/heads/internal-beta-candidate',sourceSha:sha,remoteCandidateSha:sha,treeSha:tree,baselineRef:'refs/heads/main',baselineSha:baseline,baselineTreeSha:baseline,pipelineSha256:pipeline,runId:'run-1',originalCheckoutClean:true,scanCloneVerified:true,buildCloneVerified:true,gitAlternatesRejected:true,verifiedAt:new Date().toISOString()},proofPath=join(artifact,'source/source-proof.json');writeFileSync(proofPath,JSON.stringify(proof));const proofSha=h(readFileSync(proofPath)),contextPath=join(runRoot,'source-context.json');writeFileSync(contextPath,JSON.stringify({version:1,kind:'lunchlineup-internal-ci-source-context',repository:proof.repository,runId:proof.runId,runRoot,sourceRef:proof.sourceRef,sourceSha:sha,treeSha:tree,remoteCandidateSha:sha,baselineRef:proof.baselineRef,baselineSha:baseline,pipelineSha256:pipeline,sourceProofPath:proofPath,scanSourcePath:scan,buildSourcePath:build,artifactRoot:artifact,evidenceRoot:artifact}));
const archive=Buffer.from('archive'),archivePath=join(artifact,'images/web.tar.gz');writeFileSync(archivePath,archive);const archiveSha=h(archive),imageId=`sha256:${'5'.repeat(64)}`,imageRef=`lunchlineup-internal-ci/web:${sha}`,publicSha='6'.repeat(64),manifest={version:2,kind:'lunchlineup-internal-ci-release-manifest',releaseTarget:'internal-beta',repository:proof.repository,runId:'run-1',sourceRef:proof.sourceRef,sourceSha:sha,treeSha:tree,pipelineSha256:pipeline,composeConfig:{path:'compose-config.json',sha256:'7'.repeat(64)},publicBuildConfig:{sha256:publicSha,values:{NEXT_PUBLIC_API_URL:'/api/v2',NEXT_PUBLIC_APP_ORIGIN:'https://beta.lunchlineup.com',NEXT_PUBLIC_APP_URL:'https://beta.lunchlineup.com',NEXT_PUBLIC_APP_ENV:'production',NEXT_PUBLIC_SIGNUP_MODE:'closed_beta'}},services:{web:{imageArtifact:'web'}},images:{web:{composeServices:['web'],resolvedRef:imageRef,localImageId:imageId,archive:{path:'images/web.tar.gz',sha256:archiveSha,bytes:archive.length},source:'first-party'}}},manifestPath=join(artifact,'release-manifest.json');writeFileSync(manifestPath,JSON.stringify(manifest));const manifestSha=h(readFileSync(manifestPath)),interaction={version:1,kind:'lunchlineup-internal-beta-interaction-proof',sourceSha:sha,candidateTreeSha:tree,releaseManifestSha256:manifestSha,webImageId:imageId,publicBuildConfigSha256:publicSha,cases:{},artifactPolicy:{trace:'on',video:'on',screenshot:'on'},playwrightReportSha256:'8'.repeat(64)},interactionPath=join(artifact,'interaction-proof.json');writeFileSync(interactionPath,JSON.stringify(interaction));
const sbomRaw=join(artifact,'sbom/web.spdx.json'),trivyRaw=join(artifact,'trivy/web.trivy.json');writeFileSync(sbomRaw,'{}');writeFileSync(trivyRaw,'{}');const reportBinding=(path)=>({sourceSha:sha,treeSha:tree,releaseManifestSha256:manifestSha,artifactName:'web',composeServices:['web'],imageRef,localImageId:imageId,archiveSha256:archiveSha,archiveBytes:archive.length,scannerImage:`scanner@sha256:${'9'.repeat(64)}`,report:{path:relative(artifact,path).replaceAll('\\','/'),sha256:h(readFileSync(path)),bytes:statSync(path).size}}),sbomSummary={reports:{web:reportBinding(sbomRaw)}},trivySummary={reports:{web:reportBinding(trivyRaw)}};writeFileSync(join(artifact,'sbom/summary.json'),JSON.stringify(sbomSummary));writeFileSync(join(artifact,'trivy/summary.json'),JSON.stringify(trivySummary));
const detailValues={'semgrep-full':{findings:3},'semgrep-delta':{findings:0},'codeql-javascript-typescript':{unapprovedFindings:0},'codeql-python':{unapprovedFindings:0},trivy:{high:0,critical:0}};for(const[n,v]of Object.entries(detailValues))writeFileSync(join(artifact,`details/${n}.json`),JSON.stringify({sourceSha:sha,...v}));const commonPath=join(artifact,'evidence/common.log');writeFileSync(commonPath,'passed\n');const common={path:'evidence/common.log',sha256:h(readFileSync(commonPath)),bytes:statSync(commonPath).size};
for(const name of REQUIRED_INTERNAL_BETA_GATES.filter(n=>n!=='artifact-integrity')){const gate={version:2,kind:'lunchlineup-internal-ci-gate',name,status:'passed',repository:proof.repository,runId:'run-1',sourceRef:proof.sourceRef,sourceSha:sha,treeSha:tree,baselineSha:baseline,pipelineSha256:pipeline,sourceProofSha256:proofSha,attempt:1,startedAt:new Date(Date.now()-2000).toISOString(),completedAt:new Date(Date.now()-1000).toISOString(),evidence:[common],details:{}};writeFileSync(join(artifact,`gates/${name}.json`),JSON.stringify(gate));}
const files=[];const walk=(dir)=>{for(const name of readdirSync(dir)){const path=join(dir,name);if(statSync(path).isDirectory())walk(path);else{const rel=relative(artifact,path).replaceAll('\\','/');files.push({path:rel,sha256:h(readFileSync(path)),bytes:statSync(path).size,mode:'0600'});}}};walk(artifact);files.sort((a,b)=>a.path.localeCompare(b.path));const artifactManifest={version:1,kind:'lunchlineup-internal-ci-artifact-manifest',sourceSha:sha,treeSha:tree,runId:'run-1',files,fileCount:files.length,totalBytes:files.reduce((n,x)=>n+x.bytes,0),rootSha256:h(files.map(x=>`${x.path}\0${x.sha256}\0${x.bytes}\0${x.mode}\n`).join(''))},artifactPath=join(artifact,'artifact-manifest.json');writeFileSync(artifactPath,JSON.stringify(artifactManifest));const artifactEvidence={path:'artifact-manifest.json',sha256:h(readFileSync(artifactPath)),bytes:statSync(artifactPath).size},artifactGate={version:2,kind:'lunchlineup-internal-ci-gate',name:'artifact-integrity',status:'passed',repository:proof.repository,runId:'run-1',sourceRef:proof.sourceRef,sourceSha:sha,treeSha:tree,baselineSha:baseline,pipelineSha256:pipeline,sourceProofSha256:proofSha,attempt:1,startedAt:new Date(Date.now()-2000).toISOString(),completedAt:new Date(Date.now()-1000).toISOString(),evidence:[artifactEvidence],details:{}};writeFileSync(join(artifact,'gates/artifact-integrity.json'),JSON.stringify(artifactGate));
const output=join(artifact,'candidate-receipt.json'),args=['--source-context',contextPath,'--source-proof',proofPath,'--gate-directory',join(artifact,'gates'),'--release-manifest',manifestPath,'--interaction-proof',interactionPath,'--artifact-manifest',artifactPath,'--output',output],env={...process.env,CI_COMMIT_SHA:sha,CI_RUN_ID:'run-1',CI_RUN_ATTEMPT:'1',RUNNER_TEMP:runner};return{scratch,artifact,proof,proofPath,manifest,manifestPath,interaction,interactionPath,sbomSummary,trivySummary,artifactManifest,artifactPath,output,args,env};}
const run=(f)=>spawnSync(process.execPath,[builder,...f.args],{env:f.env,encoding:'utf8'}),rewrite=(p,v)=>writeFileSync(p,JSON.stringify(v));
test('complete exact gate and image evidence builds a bounded receipt',()=>{const f=fixture();try{const r=run(f);assert.equal(r.status,0,r.stderr);const receipt=JSON.parse(readFileSync(f.output));assert.equal(Object.keys(receipt.gates).length,29);assert.match(receipt.gates.lint.sha256,/^[a-f0-9]{64}$/);assert.equal(receipt.securitySummary.semgrepDeltaFindings,0);assert.equal(Date.parse(receipt.expiresAt)-Date.parse(receipt.issuedAt),72*60*60*1000);}finally{rmSync(f.scratch,{recursive:true,force:true});}});
for(const [name,mutate]of[
 ['missing gate',(f)=>rmSync(join(f.artifact,'gates/lint.json'))],
 ['extra gate',(f)=>writeFileSync(join(f.artifact,'gates/extra.json'),'{}')],
 ['duplicate gate identity',(f)=>{const p=join(f.artifact,'gates/lint.json'),x=JSON.parse(readFileSync(p));x.name='typecheck';rewrite(p,x);}],
 ['failed gate',(f)=>{const p=join(f.artifact,'gates/lint.json'),x=JSON.parse(readFileSync(p));x.status='failed';rewrite(p,x);}],
 ['wrong source SHA',(f)=>{const p=join(f.artifact,'gates/lint.json'),x=JSON.parse(readFileSync(p));x.sourceSha='9'.repeat(40);rewrite(p,x);}],
 ['wrong tree SHA',(f)=>{const p=join(f.artifact,'gates/lint.json'),x=JSON.parse(readFileSync(p));x.treeSha='9'.repeat(40);rewrite(p,x);}],
 ['wrong baseline SHA',(f)=>{const p=join(f.artifact,'gates/lint.json'),x=JSON.parse(readFileSync(p));x.baselineSha='9'.repeat(40);rewrite(p,x);}],
 ['wrong run ID',(f)=>{const p=join(f.artifact,'gates/lint.json'),x=JSON.parse(readFileSync(p));x.runId='wrong';rewrite(p,x);}],
 ['wrong pipeline digest',(f)=>{const p=join(f.artifact,'gates/lint.json'),x=JSON.parse(readFileSync(p));x.pipelineSha256='9'.repeat(64);rewrite(p,x);}],
 ['gate evidence absent from artifact manifest',(f)=>{f.artifactManifest.files=f.artifactManifest.files.filter(x=>x.path!=='evidence/common.log');rewrite(f.artifactPath,f.artifactManifest);const p=join(f.artifact,'gates/artifact-integrity.json'),x=JSON.parse(readFileSync(p));x.evidence[0].sha256=h(readFileSync(f.artifactPath));x.evidence[0].bytes=statSync(f.artifactPath).size;rewrite(p,x);}],
 ['Semgrep delta above zero',(f)=>rewrite(join(f.artifact,'details/semgrep-delta.json'),{sourceSha:sha,findings:1})],
 ['unapproved CodeQL result',(f)=>rewrite(join(f.artifact,'details/codeql-python.json'),{sourceSha:sha,unapprovedFindings:1})],
 ['Trivy high finding',(f)=>rewrite(join(f.artifact,'details/trivy.json'),{sourceSha:sha,high:1,critical:0})],
 ['Trivy critical finding',(f)=>rewrite(join(f.artifact,'details/trivy.json'),{sourceSha:sha,high:0,critical:1})],
 ['missing SBOM for one image',(f)=>{f.sbomSummary.reports={};rewrite(join(f.artifact,'sbom/summary.json'),f.sbomSummary);}],
 ['missing Trivy for one image',(f)=>{f.trivySummary.reports={};rewrite(join(f.artifact,'trivy/summary.json'),f.trivySummary);}],
 ['extra unreferenced image report',(f)=>{f.sbomSummary.reports.extra=f.sbomSummary.reports.web;rewrite(join(f.artifact,'sbom/summary.json'),f.sbomSummary);}],
 ['archive bytes drift after artifact remanifest',(f)=>{const archivePath=join(f.artifact,'images/web.tar.gz');writeFileSync(archivePath,'tampered');const listed=f.artifactManifest.files.find((x)=>x.path==='images/web.tar.gz');listed.sha256=h(readFileSync(archivePath));listed.bytes=statSync(archivePath).size;f.artifactManifest.totalBytes=f.artifactManifest.files.reduce((n,x)=>n+x.bytes,0);f.artifactManifest.rootSha256=h(f.artifactManifest.files.map((x)=>`${x.path}\0${x.sha256}\0${x.bytes}\0${x.mode}\n`).join(''));rewrite(f.artifactPath,f.artifactManifest);const gatePath=join(f.artifact,'gates/artifact-integrity.json'),gate=JSON.parse(readFileSync(gatePath));gate.evidence[0].sha256=h(readFileSync(f.artifactPath));gate.evidence[0].bytes=statSync(f.artifactPath).size;rewrite(gatePath,gate);}],
 ['wrong public build configuration',(f)=>{f.manifest.publicBuildConfig.values.NEXT_PUBLIC_APP_URL='https://wrong.invalid';rewrite(f.manifestPath,f.manifest);}],
 ['wrong interaction proof binding',(f)=>{f.interaction.releaseManifestSha256='9'.repeat(64);rewrite(f.interactionPath,f.interaction);}],
])test(`candidate receipt builder rejects ${name}`,()=>{const f=fixture();try{mutate(f);assert.notEqual(run(f).status,0);}finally{rmSync(f.scratch,{recursive:true,force:true});}});
