import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import test from 'node:test';

const script = resolve(import.meta.dirname, '../../scripts/materialize-internal-ci-source.mjs');
const git = (cwd,...args) => { const r=spawnSync('git',args,{cwd,encoding:'utf8'}); assert.equal(r.status,0,r.stderr); return r.stdout.trim(); };
function fixture() {
  const scratch=mkdtempSync(join(tmpdir(),'ll-source-')), remote=join(scratch,'remote.git'), workspace=join(scratch,'workspace'), runner=join(scratch,'runner');
  mkdirSync(runner); git(scratch,'init','--bare',remote); git(scratch,'clone',remote,workspace); git(workspace,'config','user.email','ci@example.invalid'); git(workspace,'config','user.name','CI Test');
  mkdirSync(join(workspace,'.ci')); writeFileSync(join(workspace,'.ci/pipeline.json'),'{}\n'); writeFileSync(join(workspace,'README.md'),'main\n'); git(workspace,'add','.'); git(workspace,'commit','-m','main'); git(workspace,'branch','-M','main'); git(workspace,'push','-u','origin','main');
  git(workspace,'checkout','-b','internal-beta-candidate'); writeFileSync(join(workspace,'candidate.txt'),'candidate\n'); git(workspace,'add','.'); git(workspace,'commit','-m','candidate'); git(workspace,'push','-u','origin','internal-beta-candidate'); git(workspace,'fetch','origin');
  const sha=git(workspace,'rev-parse','HEAD'), artifact=join(workspace,'.release','internal-ci',sha), runRoot=join(runner,'lunchlineup-source-run-1');
  const env={...process.env,CI_COMMIT_SHA:sha,CI_REF:'refs/heads/internal-beta-candidate',CI_RUN_ID:'run-1',CI_RUN_ATTEMPT:'1',CI_REPOSITORY:'tuckerplee/LunchLineup',RUNNER_TEMP:runner};
  return {scratch,remote,workspace,runner,sha,artifact,runRoot,env,args:['--artifact-root',artifact,'--run-root',runRoot]};
}
const run=(f,env=f.env)=>spawnSync(process.execPath,[script,...f.args],{cwd:f.workspace,env,encoding:'utf8'});
test('clean exact candidate materializes independent exact clones and bounded proof',()=>{ const f=fixture(); try { const r=run(f); assert.equal(r.status,0,r.stderr); const proof=JSON.parse(readFileSync(join(f.artifact,'source/source-proof.json'))); assert.equal(proof.sourceSha,f.sha); assert.equal(proof.status,'passed'); assert.doesNotMatch(JSON.stringify(proof),/[A-Za-z]:[\\/]/); assert.equal(existsSync(join(f.runRoot,'source-context.json')),true); assert.equal(existsSync(join(f.artifact,'gates/source-identity.json')),true); const scan=join(f.runRoot,'scan'),build=join(f.runRoot,'build'); assert.notEqual(git(scan,'rev-parse','--absolute-git-dir'),git(build,'rev-parse','--absolute-git-dir')); writeFileSync(join(scan,'scan-only.txt'),'x'); assert.equal(existsSync(join(build,'scan-only.txt')),false); assert.equal(git(build,'status','--porcelain=v1','--untracked-files=all'),''); } finally { rmSync(f.scratch,{recursive:true,force:true}); } });
for (const [name,prepare,envChange] of [
 ['HEAD differs from controller SHA',()=>{},(f)=>({...f.env,CI_COMMIT_SHA:'9'.repeat(40)})],
 ['wrong branch',()=>{},(f)=>({...f.env,CI_REF:'refs/heads/main'})],
 ['dirty tracked file',(f)=>writeFileSync(join(f.workspace,'candidate.txt'),'dirty\n')],
 ['staged file',(f)=>{writeFileSync(join(f.workspace,'staged.txt'),'x');git(f.workspace,'add','staged.txt');}],
 ['untracked file',(f)=>writeFileSync(join(f.workspace,'untracked.txt'),'x')],
 ['remote candidate mismatch',(f)=>{writeFileSync(join(f.workspace,'local.txt'),'x');git(f.workspace,'add','.');git(f.workspace,'commit','-m','local only'); f.env.CI_COMMIT_SHA=git(f.workspace,'rev-parse','HEAD'); f.args[1]=join(f.workspace,'.release','internal-ci',f.env.CI_COMMIT_SHA);}],
 ['missing baseline',(f)=>git(f.workspace,'update-ref','-d','refs/remotes/origin/main')],
 ['wrong baseline ref',(f)=>git(f.workspace,'update-ref','refs/remotes/origin/main',f.sha)],
 ['existing scan destination',(f)=>mkdirSync(join(f.runRoot,'scan'),{recursive:true})],
 ['existing build destination',(f)=>mkdirSync(join(f.runRoot,'build'),{recursive:true})],
]) test(`materializer rejects ${name}`,()=>{ const f=fixture(); try { prepare(f); const r=run(f,envChange?envChange(f):f.env); assert.notEqual(r.status,0,`unexpected success for ${name}`); } finally { rmSync(f.scratch,{recursive:true,force:true}); } });
test('materializer refuses an existing proof/artifact root',()=>{ const f=fixture(); try { mkdirSync(join(f.artifact,'source'),{recursive:true}); writeFileSync(join(f.artifact,'source/source-proof.json'),'{}'); assert.notEqual(run(f).status,0); } finally { rmSync(f.scratch,{recursive:true,force:true}); } });
for (const cloneName of ['scan','build']) test(`materializer rejects a symlinked ${cloneName} root`,(t)=>{ const f=fixture(); try { const target=join(f.scratch,`${cloneName}-target`); mkdirSync(target); mkdirSync(f.runRoot,{recursive:true}); try { symlinkSync(target,join(f.runRoot,cloneName),process.platform==='win32'?'junction':'dir'); } catch (error) { t.skip(`directory symlinks are unavailable: ${error.code}`); return; } assert.notEqual(run(f).status,0); } finally { rmSync(f.scratch,{recursive:true,force:true}); } });
for (const cloneName of ['scan','build']) test(`downstream verifier rejects Git alternates in the ${cloneName} clone`,()=>{ const f=fixture(); try { const materialized=run(f); assert.equal(materialized.status,0,materialized.stderr); const clone=join(f.runRoot,cloneName),alternates=join(clone,'.git','objects','info','alternates'); mkdirSync(resolve(alternates,'..'),{recursive:true}); writeFileSync(alternates,join(f.workspace,'.git','objects')); const verified=spawnSync(process.execPath,[resolve(script,'../verify-internal-ci-source-clone.mjs'),'--proof',join(f.artifact,'source/source-proof.json'),'--clone',clone,'--purpose',cloneName,'--require-clean'],{encoding:'utf8'}); assert.notEqual(verified.status,0); } finally { rmSync(f.scratch,{recursive:true,force:true}); } });
test('source context rejects equal scan and build paths and a mutated clone tree',()=>{ const f=fixture(); try { const materialized=run(f); assert.equal(materialized.status,0,materialized.stderr); const contextPath=join(f.runRoot,'source-context.json'),context=JSON.parse(readFileSync(contextPath)); context.buildSourcePath=context.scanSourcePath; writeFileSync(contextPath,JSON.stringify(context)); const check=`import {readInternalCiSourceContext} from '${resolve(script,'../internal-ci-source-context.mjs').replaceAll('\\','/')}'; readInternalCiSourceContext(process.argv[1],{verifyClones:true});`; const equal=spawnSync(process.execPath,['--input-type=module','-e',check,contextPath],{env:f.env,encoding:'utf8'}); assert.notEqual(equal.status,0); context.buildSourcePath=join(f.runRoot,'build'); writeFileSync(contextPath,JSON.stringify(context)); writeFileSync(join(context.buildSourcePath,'candidate.txt'),'mutated\n'); const mutated=spawnSync(process.execPath,['--input-type=module','-e',check,contextPath],{env:f.env,encoding:'utf8'}); assert.notEqual(mutated.status,0); } finally { rmSync(f.scratch,{recursive:true,force:true}); } });
test('materializer rejects pipeline bytes changed during cloning',async()=>{ const f=fixture(); try { const child=spawn(process.execPath,[script,...f.args],{cwd:f.workspace,env:f.env,stdio:['ignore','pipe','pipe']}); let stderr=''; child.stderr.setEncoding('utf8'); child.stderr.on('data',(chunk)=>{stderr+=chunk;}); const deadline=Date.now()+10000; while(!existsSync(join(f.runRoot,'scan','.git'))&&child.exitCode===null&&Date.now()<deadline) await new Promise((resolvePromise)=>setTimeout(resolvePromise,5)); assert.equal(child.exitCode,null,`materializer exited before the pipeline mutation: ${stderr}`); writeFileSync(join(f.workspace,'.ci/pipeline.json'),'{"changed":true}\n'); const status=await new Promise((resolvePromise,reject)=>{child.once('error',reject);child.once('exit',(code)=>resolvePromise(code));}); assert.notEqual(status,0,'pipeline mutation unexpectedly passed'); assert.match(stderr,/Pipeline changed during materialization|Source is not clean/); } finally { rmSync(f.scratch,{recursive:true,force:true}); } });
