import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
const root=resolve(import.meta.dirname,'../..'),script=join(root,'scripts/internal-beta-lifecycle.sh'),source=readFileSync(script,'utf8'),bash=process.platform==='win32'?'C:\\Program Files\\Git\\bin\\bash.exe':'bash',skip=!existsSync(bash)&&process.platform==='win32';
function harness(action,body){const shell=`source '${script.replaceAll("'","'\\''")}' ${action}\ntrap - EXIT INT TERM\n${body}`;return spawnSync(bash,['-c',shell],{encoding:'utf8',env:{...process.env,BETA_CANDIDATE_SHA:'1'.repeat(40)}});}
test('launch executes signed receipt and exact image verification before providers and mutations',{skip},()=>{const r=harness('launch',`log=''; add(){ log="$log $1"; }; validate_inputs(){ add validate; }; verify_signed_internal_ci_candidate(){ add receipt; }; verify_source_and_runtime(){ add source; }; load_and_verify_candidate_images(){ add images; }; verify_resend_provider(){ add resend; }; launch_services(){ add launch; }; wait_for_services(){ add wait; }; verify_migration(){ add migration; }; verify_http_surfaces(){ add http; }; run_backup_restore_proof(){ add backup; }; verify_monitoring_and_outboxes(){ add monitoring; }; write_readiness_proof(){ add readiness; }; main; printf '%s\\n' "$log"`);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/validate receipt source images resend launch wait migration http backup monitoring readiness/);});
test('verify action also requires receipt and images before health checks',{skip},()=>{const r=harness('verify',`log=''; add(){ log="$log $1"; }; validate_inputs(){ add validate; }; verify_signed_internal_ci_candidate(){ add receipt; }; verify_source_and_runtime(){ add source; }; load_and_verify_candidate_images(){ add images; }; verify_resend_provider(){ add resend; }; wait_for_services(){ add wait; }; verify_migration(){ add migration; }; verify_http_surfaces(){ add http; }; run_backup_restore_proof(){ add backup; }; verify_monitoring_and_outboxes(){ add monitoring; }; verify_deployed_marker(){ add marker; }; write_readiness_proof(){ add readiness; }; main; printf '%s\\n' "$log"`);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/validate receipt source images resend wait migration http backup monitoring marker readiness/);});
for(const missing of ['receipt','signature'])test(`launch refuses missing ${missing} before Resend`,{skip},()=>{const variable=missing==='receipt'?'BETA_CANDIDATE_RECEIPT_FILE':'BETA_CANDIDATE_SIGNATURE_FILE';const r=spawnSync(bash,['-c',`source '${script.replaceAll("'","'\\''")}' launch\ntrap - EXIT INT TERM\nvalidate_inputs(){ :; }; verify_source_and_runtime(){ echo forbidden-source; }; verify_resend_provider(){ echo forbidden-resend; }; ${variable}=/definitely/missing; main`],{encoding:'utf8',env:{...process.env,BETA_CANDIDATE_SHA:'1'.repeat(40),[variable]:'/definitely/missing'}});assert.notEqual(r.status,0);assert.doesNotMatch(r.stdout,/forbidden/);});
test('invalid signature verifier failure stops before image loading and Resend',{skip},()=>{const r=harness('launch',`validate_inputs(){ :; }; require_root_owned_input(){ :; }; node(){ return 1; }; load_and_verify_candidate_images(){ echo forbidden-images; }; verify_resend_provider(){ echo forbidden-resend; }; main`);assert.notEqual(r.status,0);assert.doesNotMatch(r.stdout,/forbidden/);});
test('pause remains source-bound without requiring a fresh receipt',{skip},()=>{const r=harness('pause',`validate_inputs(){ :; }; git(){ [[ "$1" == -C ]] && printf '%s\\n' "$SOURCE_SHA"; }; verify_signed_internal_ci_candidate(){ echo forbidden-receipt; return 1; }; pause_services(){ echo paused-source-bound; completed=true; }; main`);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/paused-source-bound/);assert.doesNotMatch(r.stdout,/forbidden-receipt/);});
test('lifecycle source enforces archive hashes, IDs, no builds, ordering, and readiness provenance',()=>{for(const token of ['archive byte count mismatch','archive digest mismatch','loaded image ID mismatch','candidate image tag conflicts','BETA_BUILD_IMAGES','VM107 must only load qualified CI image archives','candidateReceiptSha256','candidateReceiptSignatureKeyId','releaseManifestSha256','artifactManifestSha256','artifactRootSha256','pipelineSha256','allImageIdsMatched','receiptValidAtLaunch'])assert.match(source,new RegExp(token));const receipt=source.lastIndexOf('verify_signed_internal_ci_candidate'),images=source.lastIndexOf('load_and_verify_candidate_images'),resend=source.lastIndexOf('verify_resend_provider'),launch=source.lastIndexOf('launch_services');assert.ok(receipt<images&&images<resend&&resend<launch);});
