#!/usr/bin/env bash
# Stage-oriented exact-image qualification on the Custom CI appliance. Never contacts VM107.
set -euo pipefail
[[ "${1:-}" == --source-context && -n "${2:-}" && "${3:-}" == --stage && "${4:-}" =~ ^(release-image-build|production-image-inventory|release-stack-health|fullstack-playwright|interaction-proof|dast|load|sbom|trivy)$ && $# == 4 ]] || { echo 'Usage: run-internal-beta-release-qualification.sh --source-context <context.json> --stage <stage>' >&2; exit 64; }
context=$2; stage=$4; workspace=$PWD; artifact_root="$workspace/.release/internal-ci/${CI_COMMIT_SHA:?}"; source_root="${RUNNER_TEMP:?}/lunchlineup-source-${CI_RUN_ID:?}"; build_root="$source_root/build"; qualification_root="$RUNNER_TEMP/lunchlineup-beta-qualification-$CI_RUN_ID"; env_file="$qualification_root/runtime.env"; secrets_dir="$qualification_root/secrets"; project="lunchlineup-beta-${CI_RUN_ID//[^a-zA-Z0-9]/}"
test "$context" = "$source_root/source-context.json"; test -f "$artifact_root/source/source-proof.json"; test -d "$build_root"; mkdir -p "$artifact_root/results" "$artifact_root/details"
compose=(docker compose --project-name "$project" --project-directory "$build_root" --env-file "$env_file" -f "$build_root/docker-compose.yml")
record_gate(){ local gate=$1 started=$2 details=$3; shift 3; node "$build_root/scripts/write-internal-ci-command-result.mjs" --name "$gate" --source-context "$context" --started-at "$started" --output "$artifact_root/results/$gate.json"; local evidence=(); for file in "$@"; do evidence+=(--evidence "$file"); done; node "$build_root/scripts/record-internal-ci-gate.mjs" --name "$gate" --source-context "$context" --started-at "$started" --command-result "$artifact_root/results/$gate.json" --details "$details" --output "$artifact_root/gates/$gate.json" "${evidence[@]}"; }
require_state(){ test -f "$env_file"; test -f "$artifact_root/compose-config.json"; test -f "$artifact_root/compose-image-inventory.json"; test -f "$artifact_root/release-manifest.json"; }
case "$stage" in
release-image-build)
  test ! -e "$qualification_root"; mkdir -p "$qualification_root" "$artifact_root/images"; started=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  node "$build_root/scripts/verify-internal-ci-source-clone.mjs" --proof "$artifact_root/source/source-proof.json" --clone "$build_root" --purpose build --require-clean >/dev/null
  node "$build_root/scripts/write-internal-beta-qualification-env.mjs" --source-context "$context" --output "$env_file" --public-build-config "$artifact_root/public-build-config.json" --secrets-dir "$secrets_dir"
  chmod -R a-w "$build_root"
  "${compose[@]}" --profile ops config --format json >"$artifact_root/compose-config.json"
  node "$build_root/scripts/compose-image-inventory.mjs" --source-context "$context" --compose-config "$artifact_root/compose-config.json" --runtime-contract "$build_root/infrastructure/ci/internal-beta-runtime-services.json" --output "$artifact_root/compose-image-inventory.json"
  node -e 'const x=JSON.parse(require("fs").readFileSync(process.argv[1]));for(const v of Object.values(x.images))process.stdout.write([v.source,v.composeServices[0],v.resolvedRef].join("\t")+"\n")' "$artifact_root/compose-image-inventory.json" | while IFS=$'\t' read -r source service ref; do if [[ "$source" == first-party ]]; then "${compose[@]}" --profile ops build "$service"; else docker pull "$ref"; fi; docker image inspect --format '{{.Id}}' "$ref"; done >"$artifact_root/images/build.log" 2>&1
  bash "$build_root/scripts/export-internal-ci-release-images.sh" --source-context "$context" --inventory "$artifact_root/compose-image-inventory.json" --image-directory "$artifact_root/images"
  web_ref=$(node -e 'const x=JSON.parse(require("fs").readFileSync(process.argv[1]));process.stdout.write(x.services.web.imageRef)' "$artifact_root/compose-image-inventory.json"); docker run --rm --entrypoint cat "$web_ref" /app/public/.well-known/lunchlineup-build.json >"$artifact_root/public-build-contract.json"
  node "$build_root/scripts/verify-internal-beta-public-build.mjs" --source-context "$context" --contract "$artifact_root/public-build-contract.json" --public-build-config "$artifact_root/public-build-config.json" --details "$artifact_root/details/public-build-contract.json"
  node "$build_root/scripts/write-internal-ci-release-manifest.mjs" --source-context "$context" --compose-config "$artifact_root/compose-config.json" --public-build-contract "$artifact_root/public-build-contract.json" --image-directory "$artifact_root/images" --output "$artifact_root/release-manifest.json"
  node -e 'const fs=require("fs"),x=JSON.parse(fs.readFileSync(process.argv[1]));fs.writeFileSync(process.argv[2],JSON.stringify({sourceSha:x.sourceSha,treeSha:x.treeSha,imageCount:Object.keys(x.images).length,allImagesPresent:true},null,2)+"\n",{flag:"wx",mode:0o600})' "$artifact_root/release-manifest.json" "$artifact_root/details/release-image-build.json"
  record_gate public-build-contract "$started" "$artifact_root/details/public-build-contract.json" "$artifact_root/public-build-contract.json" "$artifact_root/public-build-config.json"
  record_gate release-image-build "$started" "$artifact_root/details/release-image-build.json" "$artifact_root/images/build.log" "$artifact_root/compose-image-inventory.json" "$artifact_root/release-manifest.json"
;;
production-image-inventory)
  require_state; started=$(date -u +%Y-%m-%dT%H:%M:%SZ); node "$build_root/scripts/verify-internal-ci-production-inventory.mjs" --source-context "$context" --inventory "$artifact_root/compose-image-inventory.json" --release-manifest "$artifact_root/release-manifest.json" --output "$artifact_root/production-image-inventory.json" --details "$artifact_root/details/production-image-inventory.json"; record_gate production-image-inventory "$started" "$artifact_root/details/production-image-inventory.json" "$artifact_root/production-image-inventory.json"
;;
release-stack-health)
  require_state; started=$(date -u +%Y-%m-%dT%H:%M:%SZ); "${compose[@]}" --profile ops run --rm --no-deps migrate >"$artifact_root/migrate-release-stack.log" 2>&1
  mapfile -t services < <(node -e 'const x=JSON.parse(require("fs").readFileSync(process.argv[1]));for(const [n,v] of Object.entries(x.services))if(v.requiredOnVm107&&v.state!=="one-shot")console.log(n)' "$build_root/infrastructure/ci/internal-beta-runtime-services.json"); "${compose[@]}" --profile ops up -d --no-build --pull never --remove-orphans "${services[@]}"
  for attempt in {1..120}; do if node "$build_root/scripts/verify-internal-ci-release-stack.mjs" --source-context "$context" --release-manifest "$artifact_root/release-manifest.json" --project "$project" --output "$artifact_root/release-stack-health.json" --details "$artifact_root/details/release-stack-health.json" --probe; then break; fi; rm -f "$artifact_root/release-stack-health.json" "$artifact_root/details/release-stack-health.json"; [[ "$attempt" != 120 ]] || exit 1; sleep 5; done
  record_gate release-stack-health "$started" "$artifact_root/details/release-stack-health.json" "$artifact_root/release-stack-health.json" "$artifact_root/migrate-release-stack.log"
;;
fullstack-playwright)
  require_state; started=$(date -u +%Y-%m-%dT%H:%M:%SZ); output="$artifact_root/fullstack-playwright"; mkdir -p "$output"; cd "$build_root/apps/web"; BASE_URL=http://127.0.0.1:8080 E2E_FULL_STACK=1 E2E_MOCK_API=0 E2E_COMPOSE_PROJECT_NAME="$project" E2E_COMPOSE_ENV_FILE="$env_file" E2E_CANDIDATE_SHA="$CI_COMMIT_SHA" E2E_ARTIFACT_ROOT="$output" npx playwright test --project=chromium --workers=1 tests/e2e/operations-workflows.spec.ts tests/e2e/month-volume-workflows.spec.ts tests/e2e/stress-workflows.spec.ts tests/e2e/tenant-admin-workflows.spec.ts >"$output/test.log" 2>&1; printf '{"sourceSha":"%s","fullStack":true,"failed":0,"skipped":0}\n' "$CI_COMMIT_SHA" >"$artifact_root/details/fullstack-playwright.json"; cd "$workspace"; record_gate fullstack-playwright "$started" "$artifact_root/details/fullstack-playwright.json" "$output/test.log"
;;
interaction-proof)
  require_state; started=$(date -u +%Y-%m-%dT%H:%M:%SZ); manifest_sha=$(sha256sum "$artifact_root/release-manifest.json"|awk '{print $1}'); web_id=$(node -e 'const x=JSON.parse(require("fs").readFileSync(process.argv[1]));process.stdout.write(x.images[x.services.web.imageArtifact].localImageId)' "$artifact_root/release-manifest.json"); public_sha=$(node -e 'const x=JSON.parse(require("fs").readFileSync(process.argv[1]));process.stdout.write(x.publicBuildConfig.sha256)' "$artifact_root/release-manifest.json"); proof_dir="$artifact_root/interaction-proof-artifacts"; mkdir -p "$proof_dir"; cd "$build_root/apps/web"; E2E_CANDIDATE_SHA="$CI_COMMIT_SHA" E2E_CANDIDATE_TREE_SHA="$(git -C "$build_root" rev-parse 'HEAD^{tree}')" E2E_RELEASE_MANIFEST_SHA256="$manifest_sha" E2E_WEB_IMAGE_ID="$web_id" E2E_PUBLIC_BUILD_CONFIG_SHA256="$public_sha" E2E_INTERACTION_PROOF_ROOT="$proof_dir" npx playwright test --config=playwright.interaction-proof.config.ts >"$artifact_root/interaction-proof.log" 2>&1; node tests/e2e/verify-internal-beta-interaction-proof.mjs --report "$proof_dir/results.json" --source-sha "$CI_COMMIT_SHA" --tree-sha "$(git -C "$build_root" rev-parse 'HEAD^{tree}')" --release-manifest "$artifact_root/release-manifest.json" --web-image-id "$web_id" --public-build-config-sha256 "$public_sha" --output "$artifact_root/interaction-proof.json"; cp "$artifact_root/interaction-proof.json" "$artifact_root/details/interaction-proof.json"; cd "$workspace"; record_gate interaction-proof "$started" "$artifact_root/details/interaction-proof.json" "$artifact_root/interaction-proof.json" "$artifact_root/interaction-proof.log"
;;
dast)
  require_state; started=$(date -u +%Y-%m-%dT%H:%M:%SZ); temporary="$qualification_root/dast"; export EXPECTED_SOURCE_SHA="$CI_COMMIT_SHA" DAST_OUTPUT_DIR="$temporary" RELEASE_MANIFEST_SHA256="$(sha256sum "$artifact_root/release-manifest.json"|awk '{print $1}')"; test ! -e "$temporary"; cd "$build_root"; bash scripts/run-dast.sh http://127.0.0.1:8080; cd "$workspace"; mkdir -p "$artifact_root/dast"; cp "$temporary"/* "$artifact_root/dast/"; node "$build_root/scripts/write-internal-ci-runtime-gate-details.mjs" --source-context "$context" --gate dast --release-manifest "$artifact_root/release-manifest.json" --evidence-directory "$artifact_root/dast" --output "$artifact_root/details/dast.json"; record_gate dast "$started" "$artifact_root/details/dast.json" "$artifact_root/dast/dast-evidence-$CI_COMMIT_SHA.json"
;;
load)
  require_state; started=$(date -u +%Y-%m-%dT%H:%M:%SZ); temporary="$qualification_root/load"; export EXPECTED_SOURCE_SHA="$CI_COMMIT_SHA" LOAD_OUTPUT_DIR="$temporary" ALLOW_LOCAL_LOAD_SMOKE=true AVAILABILITY_IMPORT_TENANT_SLUG=e2e-operations AVAILABILITY_IMPORT_LOGIN_IDENTIFIER=e2e.load AVAILABILITY_IMPORT_LOGIN_PIN=246812 AVAILABILITY_IMPORT_MFA_SECRET=JBSWY3DPEHPK3PXP AVAILABILITY_IMPORT_TARGET_USER_IDENTIFIER=staff-1 AVAILABILITY_IMPORT_ORIGIN=https://beta.lunchlineup.com AVAILABILITY_IMPORT_CREDIT_SOURCE_ATTESTATION=admin-credit-grant; test ! -e "$temporary"; cd "$build_root"; bash scripts/load-test.sh http://127.0.0.1:8080; cd "$workspace"; mkdir -p "$artifact_root/load"; cp "$temporary"/* "$artifact_root/load/"; node "$build_root/scripts/write-internal-ci-runtime-gate-details.mjs" --source-context "$context" --gate load --release-manifest "$artifact_root/release-manifest.json" --evidence-directory "$artifact_root/load" --output "$artifact_root/details/load.json"; record_gate load "$started" "$artifact_root/details/load.json" "$artifact_root/load/load-evidence-$CI_COMMIT_SHA.json"
;;
sbom|trivy)
  require_state; started=$(date -u +%Y-%m-%dT%H:%M:%SZ); bash "$build_root/scripts/run-internal-ci-image-scan.sh" --source-context "$context" --kind "$stage" --release-manifest "$artifact_root/release-manifest.json"; record_gate "$stage" "$started" "$artifact_root/details/$stage.json" "$artifact_root/$stage/summary.json"; if [[ "$stage" == trivy ]]; then "${compose[@]}" --profile ops down -v --remove-orphans >/dev/null 2>&1 || true; fi
;;
esac
