import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = resolve(packageRoot, 'src/generated-client.ts');

const source = `// Generated by codegen/generate-client.mjs. Do not edit by hand.
import { Value } from '@sinclair/typebox/value';
import {
  BreakGenerationResponseSchema,
  DemandWindowListResponseSchema,
  DemandWindowReplaceResponseSchema,
  ProblemDetailsSchema,
  ScheduleBoardResponseSchema,
  ScheduleChangeSetResponseSchema,
  ScheduleCreateResponseSchema,
  SchedulePublicationResponseSchema,
  SchedulePublishPlanResponseSchema,
  ScheduleReopenResponseSchema,
  ScheduleSolveJobSchema,
  ScheduleSolveResponseSchema,
  type BreakGenerationRequest,
  type BreakGenerationResponse,
  type DemandWindowListResponse,
  type DemandWindowReplaceRequest,
  type DemandWindowReplaceResponse,
  type ProblemDetails,
  type ScheduleBoardResponse,
  type ScheduleChangeSetRequest,
  type ScheduleChangeSetResponse,
  type ScheduleCreateRequest,
  type ScheduleCreateResponse,
  type SchedulePublicationRequest,
  type SchedulePublicationResponse,
  type SchedulePublishPlanResponse,
  type ScheduleReopenResponse,
  type ScheduleSolveJob,
  type ScheduleSolveRequest,
  type ScheduleSolveResponse,
  type SchedulerView,
} from './scheduling';

const JSON_LIMIT_BYTES = 2 * 1024 * 1024;

export type ApiV2Fetch = (input: string | URL | Request, init?: RequestInit) => Promise<Response>;

export type ApiV2ClientOptions = {
  baseUrl?: string;
  fetch?: ApiV2Fetch;
};

export type ScheduleBoardQuery = {
  date: string;
  view: SchedulerView;
  locationId?: string;
};

export class ApiV2ClientError extends Error {
  readonly status: number;
  readonly problem: ProblemDetails;

  constructor(status: number, problem: ProblemDetails) {
    super(problem.detail || problem.title);
    this.name = 'ApiV2ClientError';
    this.status = status;
    this.problem = problem;
  }
}

function normalizeBaseUrl(value: string): string {
  const normalized = value.trim().replace(/\\/+$/, '');
  if (!normalized.startsWith('/') || normalized.startsWith('//') || normalized.includes('\\\\')) {
    throw new Error('API v2 client requires a same-origin base path.');
  }
  return normalized;
}

function encodeId(value: string): string {
  return encodeURIComponent(value);
}

async function readBoundedJson(response: Response): Promise<unknown> {
  const declared = Number(response.headers.get('content-length') || 0);
  if (Number.isFinite(declared) && declared > JSON_LIMIT_BYTES) {
    throw new Error('The API response exceeded the client safety limit.');
  }
  const buffer = new Uint8Array(await response.arrayBuffer());
  if (buffer.byteLength > JSON_LIMIT_BYTES) {
    throw new Error('The API response exceeded the client safety limit.');
  }
  if (buffer.byteLength === 0) return null;
  return JSON.parse(new TextDecoder().decode(buffer)) as unknown;
}

async function requestJson<T>(
  fetcher: ApiV2Fetch,
  url: string,
  init: RequestInit,
  schema: { [key: string]: unknown },
): Promise<T> {
  const response = await fetcher(url, {
    ...init,
    credentials: 'include',
    redirect: 'error',
    headers: {
      Accept: 'application/json',
      ...init.headers,
    },
  });
  const payload = await readBoundedJson(response);
  if (!response.ok) {
    const problem = Value.Check(ProblemDetailsSchema, payload)
      ? payload
      : {
          type: 'about:blank',
          title: 'Request failed',
          status: response.status,
          detail: 'The service could not complete the request.',
          code: 'request_failed',
        };
    throw new ApiV2ClientError(response.status, problem);
  }
  if (!Value.Check(schema as never, payload)) {
    throw new Error('The API returned a response that does not match its contract.');
  }
  return payload as T;
}

export function createApiV2Client(options: ApiV2ClientOptions = {}) {
  const baseUrl = normalizeBaseUrl(options.baseUrl ?? '/api/v2');
  const fetcher = options.fetch ?? globalThis.fetch.bind(globalThis);
  return {
    getScheduleBoard(query: ScheduleBoardQuery): Promise<ScheduleBoardResponse> {
      const params = new URLSearchParams({ date: query.date, view: query.view });
      if (query.locationId) params.set('locationId', query.locationId);
      return requestJson<ScheduleBoardResponse>(
        fetcher,
        \`\${baseUrl}/schedule-board?\${params.toString()}\`,
        { method: 'GET' },
        ScheduleBoardResponseSchema,
      );
    },

    createSchedule(
      locationId: string,
      request: ScheduleCreateRequest,
      idempotencyKey: string,
    ): Promise<ScheduleCreateResponse> {
      return requestJson<ScheduleCreateResponse>(
        fetcher,
        \`\${baseUrl}/locations/\${encodeId(locationId)}/schedules\`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Idempotency-Key': idempotencyKey,
          },
          body: JSON.stringify(request),
        },
        ScheduleCreateResponseSchema,
      );
    },

    applyScheduleChangeSet(
      scheduleId: string,
      request: ScheduleChangeSetRequest,
      etag: string,
      idempotencyKey: string,
    ): Promise<ScheduleChangeSetResponse> {
      return requestJson<ScheduleChangeSetResponse>(
        fetcher,
        \`\${baseUrl}/schedules/\${encodeId(scheduleId)}/change-sets\`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Idempotency-Key': idempotencyKey,
            'If-Match': etag,
          },
          body: JSON.stringify(request),
        },
        ScheduleChangeSetResponseSchema,
      );
    },

    getDemandWindows(scheduleId: string): Promise<DemandWindowListResponse> {
      return requestJson<DemandWindowListResponse>(
        fetcher,
        \`\${baseUrl}/schedules/\${encodeId(scheduleId)}/demand-windows\`,
        { method: 'GET' },
        DemandWindowListResponseSchema,
      );
    },

    replaceDemandWindows(
      scheduleId: string,
      request: DemandWindowReplaceRequest,
      etag: string,
      idempotencyKey: string,
    ): Promise<DemandWindowReplaceResponse> {
      return requestJson<DemandWindowReplaceResponse>(
        fetcher,
        \`\${baseUrl}/schedules/\${encodeId(scheduleId)}/demand-windows\`,
        {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            'Idempotency-Key': idempotencyKey,
            'If-Match': etag,
          },
          body: JSON.stringify(request),
        },
        DemandWindowReplaceResponseSchema,
      );
    },

    getSchedulePublishPlan(scheduleId: string): Promise<SchedulePublishPlanResponse> {
      return requestJson<SchedulePublishPlanResponse>(
        fetcher,
        \`\${baseUrl}/schedules/\${encodeId(scheduleId)}/publish-plan\`,
        { method: 'GET' },
        SchedulePublishPlanResponseSchema,
      );
    },

    publishSchedule(
      scheduleId: string,
      request: SchedulePublicationRequest,
      idempotencyKey: string,
    ): Promise<SchedulePublicationResponse> {
      return requestJson<SchedulePublicationResponse>(
        fetcher,
        \`\${baseUrl}/schedules/\${encodeId(scheduleId)}/publications\`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Idempotency-Key': idempotencyKey,
          },
          body: JSON.stringify(request),
        },
        SchedulePublicationResponseSchema,
      );
    },

    reopenSchedule(
      scheduleId: string,
      etag: string,
      idempotencyKey: string,
    ): Promise<ScheduleReopenResponse> {
      return requestJson<ScheduleReopenResponse>(
        fetcher,
        \`\${baseUrl}/schedules/\${encodeId(scheduleId)}/reopenings\`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Idempotency-Key': idempotencyKey,
            'If-Match': etag,
          },
          body: '{}',
        },
        ScheduleReopenResponseSchema,
      );
    },

    startScheduleSolve(
      scheduleId: string,
      request: ScheduleSolveRequest,
      idempotencyKey: string,
    ): Promise<ScheduleSolveResponse> {
      return requestJson<ScheduleSolveResponse>(
        fetcher,
        \`\${baseUrl}/schedules/\${encodeId(scheduleId)}/solve-jobs\`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Idempotency-Key': idempotencyKey,
          },
          body: JSON.stringify(request),
        },
        ScheduleSolveResponseSchema,
      );
    },

    getScheduleSolveJob(scheduleId: string, jobId: string): Promise<ScheduleSolveJob> {
      return requestJson<ScheduleSolveJob>(
        fetcher,
        \`\${baseUrl}/schedules/\${encodeId(scheduleId)}/solve-jobs/\${encodeId(jobId)}\`,
        { method: 'GET' },
        ScheduleSolveJobSchema,
      );
    },

    generateBreaks(
      request: BreakGenerationRequest,
      idempotencyKey: string,
    ): Promise<BreakGenerationResponse> {
      return requestJson<BreakGenerationResponse>(
        fetcher,
        \`\${baseUrl}/break-generations\`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Idempotency-Key': idempotencyKey,
          },
          body: JSON.stringify(request),
        },
        BreakGenerationResponseSchema,
      );
    },
  };
}
`;

writeFileSync(target, source, 'utf8');
